/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Batch Size (per node): Batch Size (per node):  Batch Size (per node):  3Batch Size (per node):  3
 3
Learning Rate: 3
Learning Rate:  
Learning Rate:  0.0001Learning Rate:  0.0001
 0.0001
0.0001

DEVICES:  [<torch.cuda.device object at 0x147f83fe14c0>, <torch.cuda.device object at 0x147f83fe1490>, <torch.cuda.device object at 0x147f83fe1310>, <torch.cuda.device object at 0x147f83fe14f0>]
DEVICES:  [<torch.cuda.device object at 0x149e6ef7b4c0>, <torch.cuda.device object at 0x149e6ef7b550>, <torch.cuda.device object at 0x149e6ef7b3d0>, <torch.cuda.device object at 0x149e6ef7b5b0>]
DEVICES:  [<torch.cuda.device object at 0x14758abdb490>, <torch.cuda.device object at 0x14758abdb520>, <torch.cuda.device object at 0x14758abdb3a0>, <torch.cuda.device object at 0x14758abdb580>]
DEVICES:  [<torch.cuda.device object at 0x154c13803460>, <torch.cuda.device object at 0x154c138034f0>, <torch.cuda.device object at 0x154c13803370>, <torch.cuda.device object at 0x154c13803550>]
Traceback (most recent call last):
  File "/panfs/ccds02/nobackup/people/kli3/RNALearner/scout_pretrain.py", line 157, in <module>
    data = sc.read_h5ad(args.data_path)
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 224, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'data/recount3/kmeans30/preprocessed_mouse_gene2vec_15117_compa2ible_bulk_only_cluster_2.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/panfs/ccds02/nobackup/people/kli3/RNALearner/scout_pretrain.py", line 157, in <module>
  File "/panfs/ccds02/nobackup/people/kli3/RNALearner/scout_pretrain.py", line 157, in <module>
Traceback (most recent call last):
  File "/panfs/ccds02/nobackup/people/kli3/RNALearner/scout_pretrain.py", line 157, in <module>
        data = sc.read_h5ad(args.data_path)data = sc.read_h5ad(args.data_path)

  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 224, in read_h5ad
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 224, in read_h5ad
    data = sc.read_h5ad(args.data_path)
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 224, in read_h5ad
        with h5py.File(filename, "r") as f:with h5py.File(filename, "r") as f:

  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 424, in __init__
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 424, in __init__
    with h5py.File(filename, "r") as f:
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 424, in __init__
        fid = make_fid(name, mode, userblock_size,fid = make_fid(name, mode, userblock_size,

  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 190, in make_fid
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = make_fid(name, mode, userblock_size,
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/h5py/_hl/files.py", line 190, in make_fid
        fid = h5f.open(name, flags, fapl=fapl)fid = h5f.open(name, flags, fapl=fapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSErrorOSError: : Unable to open file (unable to open file: name = 'data/recount3/kmeans30/preprocessed_mouse_gene2vec_15117_compa2ible_bulk_only_cluster_2.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)Unable to open file (unable to open file: name = 'data/recount3/kmeans30/preprocessed_mouse_gene2vec_15117_compa2ible_bulk_only_cluster_2.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
OSError
: Unable to open file (unable to open file: name = 'data/recount3/kmeans30/preprocessed_mouse_gene2vec_15117_compa2ible_bulk_only_cluster_2.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1191132) of binary: /home/kli3/.conda/envs/scbert/bin/python3
Traceback (most recent call last):
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scout_pretrain.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-04-01_18:30:52
  host      : gpu011.atstor.adapt.nccs.nasa.gov
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1191133)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-04-01_18:30:52
  host      : gpu011.atstor.adapt.nccs.nasa.gov
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1191134)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-04-01_18:30:52
  host      : gpu011.atstor.adapt.nccs.nasa.gov
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1191135)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-01_18:30:52
  host      : gpu011.atstor.adapt.nccs.nasa.gov
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1191132)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
JobID        JobIDRaw        JobName  Partition  MaxVMSize  MaxVMSizeNode  MaxVMSizeTask  AveVMSize     MaxRSS MaxRSSNode MaxRSSTask     AveRSS MaxPages MaxPagesNode   MaxPagesTask   AvePages     MinCPU MinCPUNode MinCPUTask     AveCPU   NTasks  AllocCPUS    Elapsed      State ExitCode AveCPUFreq ReqCPUFreqMin ReqCPUFreqMax ReqCPUFreqGov     ReqMem ConsumedEnergy  MaxDiskRead MaxDiskReadNode MaxDiskReadTask    AveDiskRead MaxDiskWrite MaxDiskWriteNode MaxDiskWriteTask   AveDiskWrite    ReqTRES  AllocTRES TRESUsageInAve TRESUsageInMax TRESUsageInMaxNode TRESUsageInMaxTask TRESUsageInMin TRESUsageInMinNode TRESUsageInMinTask TRESUsageInTot TRESUsageOutMax TRESUsageOutMaxNode TRESUsageOutMaxTask TRESUsageOutAve TRESUsageOutTot 
------------ ------------ ---------- ---------- ---------- -------------- -------------- ---------- ---------- ---------- ---------- ---------- -------- ------------ -------------- ---------- ---------- ---------- ---------- ---------- -------- ---------- ---------- ---------- -------- ---------- ------------- ------------- ------------- ---------- -------------- ------------ --------------- --------------- -------------- ------------ ---------------- ---------------- -------------- ---------- ---------- -------------- -------------- ------------------ ------------------ -------------- ------------------ ------------------ -------------- --------------- ------------------- ------------------- --------------- --------------- 
36514484     36514484      rc3scout2    compute                                                                                                                                                                                                              32   00:00:33    RUNNING      0:0                  Unknown       Unknown       Unknown       720G                                                                                                                                          billing=3+ billing=3+                                                                                                                                                                                                                                 
36514484.ba+ 36514484.ba+      batch                                                                                                                                                                                                               1         32   00:00:33    RUNNING      0:0          0             0             0             0                         0                                                                                                                                      cpu=32,gr+                                                                                                                                                                                                                                 
